### ISSUE TITLE
Where to find the CAD?

### ISSUE THREAD

**Issue by GhostJustice** [Dev-CasperTheGhost/snaily-cad#4]
What is the URL I should head to once I have set the CAD up? I am currently testing on localhost to see if this outperforms my current CAD system.

**Comment by casperiv0** [comment]
If you haven't changed the "ProductionPort", then it should output to http://localhost:80/
It should also show in the console after you run it, "Running on the_selected_port"

Hope it helps!
Casper

**Comment by GhostJustice** [comment]
see I head to that but it just directs me to the xampp dashboard?

**Comment by GhostJustice** [comment]
ha I have found it for some reason port 80 takes me to the xampp site so i changed it to 3001 and it worked. Now question how would I get this up and running so its on a domain I own etc? Like a sub domain such as cad.sacrp.net?

**Comment by casperiv0** [comment]
You will most likely need to change the port back to 80, you can stop the apache server in XAMPP since you only need the MySQL server. Your website host provider should explain how you setup sub domain names. 

Sorry I can't help too much, I don't really use domains.

I did find these articles if you'd need more help setting up a sub domain:

- https://stackoverflow.com/questions/30951466/how-to-create-subdomain-for-user-in-node-js
- https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04#set-up-reverse-proxy-server
- https://caffeinecoding.com/setting-up-subdomains-on-one-express-app-in-heroku/

**Comment by GhostJustice** [comment]
Ah its cool thanks mate really loving the CAD!! Got a couple of suggestions will post them now!

**Comment by casperiv0** [comment]
Thanks a lot! And sounds good

Stay safe!
